# Generated by Django 5.2.4 on 2025-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heim_customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
