# Generated by Django 5.2.4 on 2025-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heim_customers", "0002_alter_customer_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(
                editable=False,
                max_length=14,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
