# Generated by Django 6.0 on 2025-12-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(
                        editable=False,
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("given_names", models.CharField(max_length=32)),
                ("surnames", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["surnames", "given_names"],
                "db_table": "customers_customer",
            },
        ),
    ]
