# Generated by Django 6.0 on 2025-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotorVehicle",
            fields=[
                (
                    "vin",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("license_plate", models.CharField(blank=True, max_length=16)),
                ("license_plate_state", models.CharField(blank=True, max_length=32)),
                ("make", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("year", models.PositiveIntegerField()),
                ("mileage_km", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "motor_vehicles",
                "ordering": ["-year", "make", "model"],
            },
        ),
    ]
