# Generated by Django 6.0 on 2025-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotorVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("license_plate", models.CharField(blank=True, max_length=16)),
                ("license_plate_state", models.CharField(blank=True, max_length=32)),
                ("make", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("year", models.PositiveIntegerField()),
                ("color", models.CharField(blank=True, max_length=32)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("lpg", "LPG"),
                        ],
                        default="petrol",
                        max_length=16,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic"),
                            ("cvt", "CVT"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "engine_capacity_cc",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("mileage_km", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("scrapped", "Scrapped"),
                            ("stolen", "Stolen"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "motor_vehicles",
                "ordering": ["-year", "make", "model"],
            },
        ),
    ]
