# Generated by Django 6.0 on 2025-12-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_address'),
        ('motor_vehicle_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorvehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='customer_management.customer'),
        ),
    ]
