# Generated by Django 6.0 on 2025-12-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0002_address"),
        ("motor_vehicle_services", "0002_motorvehicle_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("renew", "Renew"),
                            ("transfer", "Transfer"),
                            ("renew_rdf", "Renew RDF"),
                            ("transfer_rdf", "Transfer RDF"),
                            ("duplicate_title", "Duplicate Title"),
                            ("replacement_credentials", "Replacement Credentials"),
                        ],
                        default="renew",
                        max_length=32,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="customer_management.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="motor_vehicle_services.motorvehicle",
                    ),
                ),
            ],
            options={
                "db_table": "motor_vehicle_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
