# Generated by Django 6.0 on 2025-12-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("motor_vehicle_services", "0003_add_transaction_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motorvehicle",
            name="mileage_km",
        ),
    ]
