# Generated by Django 6.0 on 2025-12-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor_vehicle_services', '0003_add_transaction_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorvehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='motorvehicle',
            name='engine_capacity_cc',
        ),
        migrations.RemoveField(
            model_name='motorvehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='motorvehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='motorvehicle',
            name='transmission',
        ),
    ]
