# Generated by Django 6.0 on 2025-12-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_vehicle_services', '0004_remove_mileage_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('renew', 'Renew'), ('transfer', 'Transfer'), ('renew_rdf', 'Renew RDF'), ('transfer_rdf', 'Transfer RDF'), ('duplicate_title', 'Duplicate Title'), ('replacement_credentials', 'Replacement Credentials'), ('transfer_clear', 'Transfer Clear'), ('lien_sale', 'Lien Sale'), ('nrl', 'Notice of Transfer and Release of Liability')], default='renew', max_length=32),
        ),
    ]
