# Generated by Django 6.0 on 2025-12-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_vehicle_services', '0004_remove_vehicle_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('renew', 'Renew'), ('transfer', 'Transfer'), ('renew_rdf', 'Renew RDF'), ('transfer_rdf', 'Transfer RDF'), ('duplicate_title', 'Duplicate Title'), ('replacement_credentials', 'Replacement Credentials')], default='renew', max_length=32),
        ),
    ]
