# Generated by Django 6.0 on 2025-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_vehicle_services', '0005_add_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('RNW', 'Renew'), ('TNSF', 'Transfer'), ('RNWRDF', 'Renew RDF'), ('TNSFRDF', 'Transfer RDF'), ('DUPTTL', 'Duplicate Title'), ('RPLCRD', 'Replacement Credentials'), ('TNSFCLR', 'Transfer Clear'), ('LNSL', 'Lien Sale'), ('NTRL', 'Notice of Transfer and Release of Liability')], default='RNW', max_length=32),
        ),
    ]
